---
title: "Documentation"
---

### Step 1: Prepare Data 

LogFSM can analyze log data from different sources. Different input formats are supported: 

- CSV file with one line for each event (PersonIdentifier, TimeStamp or RelativeTime, EventName, and Element are required, any key-value pair of event-specific data is possible)
- XML data generated with the Execution Environment of the CBA ItemBuilder (before version 8.12)
- JSON data generated with the deployment software for the CBA ItemBuilder (version 9.0 and newer)
- CSV data exported from the PIAAC LogFileAnalyzer
- Direct import for additional data formats is under development

Data of any format can be transformed into the structure of a flat data table in R before using this data with LogFSM.  

### Step 2: Define Finite-State Machine

LogFSM requires to specify a finite-state machine in a simple syntax. 
 
### Step 3: Reconstruct Sequence of States

The finite-state machine(s), defined in step 2, the log data are analyzed, and the sequence of states is reconstructed.

### Step 4: Read Output Tables and Create Process Indicators in R 

From the reconstructed sequence of states, LogFSM creates various output tables and graphs that can be used to extract indicators. 
