name: LogFSM Build Windows Binary Package (Master) 

on:
  push:
    branches:    
      - master         

jobs:
  build_r_package:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
  
    - run: echo "Building Version $GITHUB_WORKSPACE/"
      shell: bash  
 
    - name: Read Version from R Package
      run: echo "::set-env name=VERSION::$(grep -o 'Version:[[:blank:]]\{0,}\[[:digit:]\.]*' \"$GITHUB_WORKSPACE/r/DESCRIPTION\" | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')"
 
    - name: Determine Shortened Hash 
      run: echo "::set-env name=HASH::$(git log --pretty=format:'%h' -n 1)"      
     
    - run: echo "Building Version $VERSION ($HASH)"
      shell: bash
 