name: LogFSM Build Windows Binary Package (Master) 

on:
  push:
    branches:    
      - develop         

jobs:
  build_r_package:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
 
    - name: Read Version from R Package
      run: echo "::set-env name=VERSION::$(grep "Version:" r/DESCRIPTION | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')"
      shell: bash      

    - name: Determine Shortened Hash 
      run: echo "::set-env name=HASH::$(git log --pretty=format:'%h' -n 1)"      
     
    - run: echo "Building Version $VERSION ($HASH)"
      shell: bash
 
    - name: Setup R Environment
      uses: r-lib/actions/setup-r@master
   
    - name: Build R Binary Package (Windows) 
      run: Rscript -e "getwd()"
      shell: bash            
            
    - name: Build R Binary Package (Windows) 
      run: Rscript -e "pkgbuild::build(path='D://a//LogFSM//LogFSM//r//', binary = TRUE)"
      shell: bash
      
    - uses: actions/upload-artifact@v1
      with:
        name: ${{format('Win_Binary_LogFSM_{0}.zip', env.VERSION)}}
        path: ${{format('LogFSM_{0}.zip', env.VERSION)}}
 