name: LogFSM Build Windows Binary Package (Master) 

on:
  push:
    branches:    
      - master         

jobs:
  build_r_package:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
 
    - name: Test2
      run: echo "::set-env name=VERSION::$(grep "Version:" /r/DESCRIPTION | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')"
      shell: bash      