name: LogFSM Build Windows Binary Package (Master) 

on:
  push:
    branches:    
      - master         

jobs:
  build_r_package:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
 

    - run: echo "::set-env name=GITHUB_WORKSPACE_Win::${{ github.workspace }}"
      shell: bash  
     
    - run: echo "::set-env name=GITHUB_WORKSPACE_Bash::$( $GITHUB_WORKSPACE_Wi | sed 's/\\/\//g' | sed 's/://')"
      shell: bash        
      
      
    - run: echo "Building Version $GITHUB_WORKSPACE_Win ($GITHUB_WORKSPACE_Bash)"
      shell: bash