name: LogFSM Package Build Script 

on: [push]

jobs:
  build_r_package:

    runs-on: ubuntu-latest

    steps:

    - name: Hello world
      run: echo Hello world $GITHUB_WORKSPACE

    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' 
        
    - name: Build Dotnet Worker 1
      run: dotnet build vs/LogFSMCore.sln -c Release
    - name: Build Dotnet Worker  2
      run: mkdir $GITHUB_WORKSPACE/r/inst
    - name: Build Dotnet Worker 3
      run: mkdir $GITHUB_WORKSPACE/r/inst/extdata
           
    - name: 'Publish Linux Worker 1'      
      run: mkdir $GITHUB_WORKSPACE/r/inst/extdata/linux-x64 
      
    - name: 'Publish Linux Worker 2'   
      run: dotnet publish vs/LogFSMCore.sln -c release -r ubuntu.16.10-x64 -o "$GITHUB_WORKSPACE/r/inst/extdata/linux-x64"

    - name: Setup R Environment
      uses: r-lib/actions/setup-r@master
      
    - name: Install Dependencies
      run: Rscript -e "install.packages(c('rcmdcheck','knitr','dplyr', 'curl', 'jsonlite', 'XML', 'ggplot2', 'Rmisc', 'TraMineR', 'rmarkdown', 'rappdirs'))"  
            
    - name: Check R package
      run: Rscript -e "rcmdcheck::rcmdcheck(path='r/', args = '--no-manual', error_on = 'error')"
  
    - name: Build R package
      run: Rscript -e "pkgbuild::build(path='r/')"

    - name: Display the path
      run: echo ${env:PATH}
      shell: pwsh
    
    - uses: actions/upload-artifact@v1
      with:
        name: dotnetcore worker - MacOS
        path: ${{ github.workspace }}/LogFSM_0.3.1.0.tar.gz
      name: 'Upload Package'