name: LogFSM Package Build Script 

on: [push]

jobs:

  build_dotnet_core_worker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' 
    - name: Build with dotnet
      run: dotnet build vs/LogFSMCore.sln -c Release
    - run: mkdir ${{ github.workspace }}/r/inst
    - run: mkdir ${{ github.workspace }}/r/inst/extdata
    - run: mkdir ${{ github.workspace }}/r/inst/extdata/win-x64
    - name: 'Publish with dotnet 1/3'
      run: dotnet publish vs/LogFSMCore.sln -c release -r win7-x64 -o "${{ github.workspace }}/r/inst/extdata/win-x64"

    - uses: r-lib/actions/setup-r@master
    - name: Install dependencies
      run: Rscript -e "install.packages(c('rcmdcheck'))"  
    - name: Check
      run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
  