name: LogFSM Package Build Script 

on: [push]

jobs:
  build_r_package:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
     
    - name: Read Version from R Package
      run: echo "::set-env name=VERSION::$(grep "Version:" ${{ github.workspace }}/r/DESCRIPTION | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')"
      shell: bash
 
    - name: Determine Shortened Hash 
      run: echo "::set-env name=HASH::$(git log --pretty=format:'%h' -n 1)"      
     
    - run: echo "Building Version $VERSION ($HASH)"
      shell: bash

   