name: LogFSM Package Build Script 

on: [push]

jobs:
  build_r_package:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    
    - run: echo "::set-env name=VERSION::$(grep -Po '(?<=Version:.)([0-9]|\.)*(?=\s|$)' r/DESCRIPTION)"
      shell: bash
      
   - run: echo "Building Version $VERSION)"
      shell: bash      
      