name: LogFSM Package Build Script 

on: [push]

jobs:
  build_r_package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' 
        
    - name: Build Dotnet Worker 
      run: dotnet build vs/LogFSMCore.sln -c Release
      run: mkdir ${{ github.workspace }}/r/inst
      run: mkdir ${{ github.workspace }}/r/inst/extdata
      
    - name: 'Create Windows Worker'      
      run: mkdir ${{ github.workspace }}/r/inst/extdata/win-x64
      run: dotnet publish vs/LogFSMCore.sln -c release -r win7-x64 -o "${{ github.workspace }}/r/inst/extdata/win-x64"

    - name: 'Create Linux Worker'      
      run: mkdir ${{ github.workspace }}/r/inst/extdata/linux-x64
      run: dotnet publish vs/LogFSMCore.sln -c release -r ubuntu.16.10-x64 -o "${{ github.workspace }}/r/inst/extdata/linux-x64"

    - name: 'Create MacOS Worker'      
      run: mkdir ${{ github.workspace }}/r/inst/extdata/osx-x64
      run: dotnet publish vs/LogFSMCore.sln -c release -r osx.10.12-x64 -o "${{ github.workspace }}/r/inst/extdata/osx-x64"

    - name: Setup R Environment
      uses: r-lib/actions/setup-r@master
      
    - name: Install Dependencies
      run: Rscript -e "install.packages(c('rcmdcheck','knitr','dplyr', 'curl', 'jsonlite', 'XML', 'ggplot2', 'Rmisc', 'TraMineR', 'rmarkdown', 'rappdirs'))"  
   
    - name: Build R package
      run: Rscript -e "pkgbuild::build(path='r/')"

    - uses: actions/upload-artifact@v1
      with:
        name: dotnetcore worker - MacOS
        path: ${{ github.workspace }}/LogFSM_0.3.1.0.tar.gz
      name: 'Upload Package'