name: .NET Core Build Worker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' 
    - name: Build with dotnet
      run: dotnet build vs/LogFSMCore.sln -c Release
    - name: Publish with dotnet 1/3
      run: dotnet publish vs/LogFSMCore.sln -c release -r win7-x64 -o bin/dist/win-x64
    - name: Publish with dotnet 2/3
      run: dotnet publish vs/LogFSMCore.sln -c release -r ubuntu.16.10-x64 -o bin/dist/linux-64
    - name: Publish with dotnet 3/3
      run: dotnet publish vs/LogFSMCore.sln -c release -r osx.10.12-x64 -o bin/dist/osx-x64